### ISSUE TITLE
Rust Book updates

### ISSUE THREAD

**Issue by sts10** [srishanbhattarai/trpl-redirect#1] opened 2019-02-06 14:16 UTC
Just wanted to bring your attention to the work done surrounding [this issue on the book's repo](https://github.com/rust-lang/book/issues/1802) that _appears_ to at least help mollify the problem that this project sets out to solve. Just wanted to let you know about it. 

I guess since the fixes they made don't actually do a _redirect_, it's not as smoother as the experience users get with your extension though?

**Comment by srishanbhattarai** [comment] 2019-02-06 14:54
I was hoping someone would raise this issue, so first - thank you! I have a rather long-winded response.

I actually _was_ aware that there was an open issue for this before I wrote the extension and also of course that this extension would not be needed once those fixes landed. As I wrote in one of the [comments](https://www.reddit.com/r/rust/comments/an5kts/a_browser_extension_to_redirect_outdated_links_to/efrs5g8/?context=3) on my Reddit post, I personally am too lazy to click that one extra link so a redirect works well for me. The heuristics that I use seem to be accurate enough that I don't need the fixes made in those issues to help me get to the right page. 

On a side note: I thought that it would help expedite the efforts to get the fixes landed because someone taking the time to write a browser extension solely to handle [frustrations](https://www.reddit.com/r/rust/comments/am33qj/can_the_second_edition_book_please_return_a_301/) caused by simple documentation lapses wasn't something the maintainers of the book want to have happened. Of course, I appreciate their efforts and know that they are swamped, but maybe hitting the top page in the subreddit nudged some of the maintainers and contributors to just go out and do it? haha. I don't know.

**Closed** 2019-02-06 15:03 UTC
